let
    Source = Folder.Files("C:\Users\8216609\OneDrive - Standard Chartered Bank\Desktop\PB_Survey\2025\Qual\Apr"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"CallDate", type date}, {"CallTime", type datetime}, {"CustomerID", type text}, {"CustomerIDTxt", type text}, {"ProductType", type text}, {"AgentID", Int64.Type}, {"PrimaryCallType", type text}, {"SecondaryCallType", type text}, {"CallType", type text}, {"ConnectionID", Int64.Type}, {"Duration", Int64.Type}, {"LOB", type text}, {"SupervisorID", Int64.Type}, {"ManagerID", Int64.Type}, {"CallActivityLog", Int64.Type}, {"Email", type any}, {"Segment", type text}, {"First Name", type text}, {"CallMonth", type text}, {"CallYear", Int64.Type}}),
    #"Appended Query" = Table.Combine({#"Changed Type", #"RealTime"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Appended Query",{"RMN"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Removed Columns1",{{"AgentID", type text}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type4", {"AgentID"}, #"Team List", {"logid"}, "Team List", JoinKind.LeftOuter),
    #"Expanded Columns" = Table.ExpandTableColumn(#"Merged Queries", "Team List", {"logid", "Emp Name", "Team Leader", "Manager", "Affluent", "Location"}, {"logid", "Emp Name", "Team Leader", "Manager", "Affluent", "Location"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Columns",{{"CallActivityLog", type text}}),
    #"Merged Queries1" = Table.NestedJoin(#"Changed Type1", {"CallActivityLog"}, Response, {"CallActivityLog"}, "Response", JoinKind.LeftOuter),
    #"Expanded Response" = Table.ExpandTableColumn(#"Merged Queries1", "Response", {"Response Type", "Officer CSAT", "(Group) Q4_NPS_GROUP", "NPS", "Query Resolution", "FCR", "CallActivityLog"}, {"Response Type", "Officer CSAT", "(Group) Q4_NPS_GROUP", "NPS", "Query Resolution", "FCR", "CallActivityLog.1"}),
    #"Removed Duplicates" = Table.Distinct(#"Expanded Response", {"CallActivityLog"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates",null,"No Response",Replacer.ReplaceValue,{"(Group) Q4_NPS_GROUP"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value",{{"CallMonth", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"Source.Name"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [CallMonth] <> "Mar" and [CallMonth] <> "3"),
    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Survey trigger types", each if Text.Contains([CallType], "Survey POC") then "Real Time" else if List.MatchesAny(Text.ToList([CallMonth]), each Text.Select(_,{"0".."9"}) <> "") then "NRMN" else "RMN"),
    #"Filtered Rows1" = Table.SelectRows(#"Added Custom", each true),
    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows1","(blank)","Personal",Replacer.ReplaceText,{"Segment"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Premium Banking","Premium",Replacer.ReplaceText,{"Segment"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Personal Banking","Personal",Replacer.ReplaceText,{"Segment"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Priority Banking","Priority",Replacer.ReplaceText,{"Segment"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Business Banking","Business",Replacer.ReplaceText,{"Segment"}),
    #"Added Custom1" = Table.AddColumn(#"Replaced Value5", "Final FCR", each if [Query Resolution] = "Yes" and [FCR] = "Yes" then "Yes" else "No"),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"Final FCR", type text}}),
    #"Filtered Rows2" = Table.SelectRows(#"Changed Type3", each ([CallDate] <> null)),
    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows2", "CallDate", "CallDate - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"CallDate - Copy", "Weeks"}}),
    #"Inserted Week of Month" = Table.AddColumn(#"Renamed Columns", "Week of Month", each Date.WeekOfMonth([Weeks]), Int64.Type),
    #"Changed Type5" = Table.TransformColumnTypes(#"Inserted Week of Month",{{"Week of Month", type text}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type5", "Weekly", each if [Week of Month] = "1" then "Week 1" else if [Week of Month] = "2" then "Week 2" else if [Week of Month] = "3" then "Week 3" else if [Week of Month] = "4" then "Week 4" else if [Week of Month] = "5" then "Week 4" else "NOT Found"),
    #"Removed Columns2" = Table.RemoveColumns(#"Added Conditional Column",{"Weeks", "Week of Month"})
in
    #"Removed Columns2"
